"""
import_finra.py — Convert FINRA's margin-statistics spreadsheet into the CSV
the dashboard reads.
============================================================================

FINRA publishes margin statistics monthly, about three weeks after month end,
as an .xlsx download from:

    https://www.finra.org/investors/insights/investing/margin-statistics

That spreadsheet's shape is stable but not the shape `margin_debt.py` wants, so
this script does the translation. Run it once a month after downloading the
fresh file — it is the whole "update margin debt" chore:

    python3 import_finra.py                     # uses the default paths below
    python3 import_finra.py --xlsx path/to.xlsx --csv data/margin_debt.csv
    python3 import_finra.py --months 60         # keep only the last 60 months

What it does
------------
  * Reads the "Customer Margin Balances" sheet (name is matched loosely, so a
    FINRA rename of the sheet does not break it).
  * Maps FINRA's four columns onto the dashboard's schema.
  * Sorts oldest-first and normalises "2026-06" into "2026-06-01".
  * Sets is_placeholder=FALSE on every row — this is real data, so the
    dashboard's leverage component switches from excluded to scored.
  * Prints the headline leverage numbers so you can sanity-check the import
    against what the dashboard then shows.

UNITS: FINRA reports in millions of USD. That is exactly what the dashboard
expects, so nothing is rescaled here. A value of 1,502,072 means $1.502tn.
"""

from __future__ import annotations

import argparse
import sys
from pathlib import Path

import pandas as pd

HERE = Path(__file__).parent
DEFAULT_XLSX = HERE / "data" / "margin-statistics.xlsx"
DEFAULT_CSV = HERE / "data" / "margin_debt.csv"

# FINRA's column headings -> our schema. Matched by "does the FINRA heading
# contain all these words", so minor wording changes on their side still work.
COLUMN_PATTERNS: dict[str, tuple[str, ...]] = {
    "debit_balances_musd": ("debit", "margin"),
    "free_credit_cash_musd": ("free credit", "cash"),
    "free_credit_margin_musd": ("free credit", "margin"),
}

OUT_COLUMNS = [
    "month",
    "debit_balances_musd",
    "free_credit_cash_musd",
    "free_credit_margin_musd",
    "is_placeholder",
]

CSV_HEADER = """\
# =============================================================================
# FINRA MARGIN STATISTICS — REAL DATA
# =============================================================================
# Generated by import_finra.py from FINRA's published spreadsheet.
# Source: https://www.finra.org/investors/insights/investing/margin-statistics
#
# UNITS: millions of USD (FINRA's own unit — do not rescale).
# month: first day of the month the figure refers to.
# is_placeholder: FALSE on every row, so the dashboard scores the leverage
#                 component instead of excluding it.
#
# TO UPDATE (monthly, ~2 minutes):
#   1. Download the latest spreadsheet from the FINRA link above.
#   2. Save it over data/margin-statistics.xlsx
#   3. python3 import_finra.py
# =============================================================================
"""


def find_header_row(raw: pd.DataFrame) -> int:
    """
    Locate the header row.

    FINRA sometimes ships a title/notes block above the real header, so we scan
    for the first row that mentions both a date column and a debit column
    rather than assuming row 0.
    """
    for i in range(min(15, len(raw))):
        joined = " ".join(str(v).lower() for v in raw.iloc[i].tolist())
        if "debit" in joined and ("year" in joined or "month" in joined):
            return i
    return 0


def resolve_columns(header: list[str]) -> dict[str, int]:
    """Map our schema names onto FINRA's column positions."""
    lowered = [str(h).lower() for h in header]
    resolved: dict[str, int] = {}

    for field, patterns in COLUMN_PATTERNS.items():
        for idx, name in enumerate(lowered):
            if idx in resolved.values():
                continue  # each FINRA column feeds exactly one field
            if all(p in name for p in patterns):
                resolved[field] = idx
                break
    return resolved


def load(xlsx_path: Path) -> pd.DataFrame:
    """Read the spreadsheet into the dashboard's schema."""
    book = pd.ExcelFile(xlsx_path)

    sheet = next(
        (s for s in book.sheet_names if "margin" in s.lower() or "balance" in s.lower()),
        book.sheet_names[0],
    )
    raw = book.parse(sheet, header=None)

    header_row = find_header_row(raw)
    header = raw.iloc[header_row].tolist()
    body = raw.iloc[header_row + 1:].reset_index(drop=True)

    cols = resolve_columns(header)
    missing = [f for f in COLUMN_PATTERNS if f not in cols]
    if "debit_balances_musd" in missing:
        raise SystemExit(
            f"Could not find the debit-balances column in '{sheet}'.\n"
            f"Headings seen: {header}\n"
            "FINRA may have changed the layout — adjust COLUMN_PATTERNS."
        )

    out = pd.DataFrame()
    # The date column is whichever one we did NOT map to a value field.
    value_positions = set(cols.values())
    date_pos = next(i for i in range(len(header)) if i not in value_positions)

    out["month"] = pd.to_datetime(
        body.iloc[:, date_pos].astype(str).str.strip(), errors="coerce"
    )
    for field in ("debit_balances_musd", "free_credit_cash_musd", "free_credit_margin_musd"):
        if field in cols:
            out[field] = pd.to_numeric(body.iloc[:, cols[field]], errors="coerce")
        else:
            out[field] = pd.NA
            print(f"  note: FINRA column for {field} not found — left blank", file=sys.stderr)

    out = out.dropna(subset=["month", "debit_balances_musd"])
    out = out.sort_values("month").reset_index(drop=True)
    out["is_placeholder"] = "FALSE"
    return out[OUT_COLUMNS]


def summarise(df: pd.DataFrame) -> None:
    """Print the headline leverage numbers the dashboard will derive."""
    d = df.set_index("month")["debit_balances_musd"]
    latest, latest_month = float(d.iloc[-1]), d.index[-1]

    peak, peak_month = float(d.max()), d.idxmax()
    pct_of_peak = latest / peak * 100

    target = latest_month - pd.DateOffset(months=12)
    prior = d.loc[:target]
    yoy = (latest / float(prior.iloc[-1]) - 1) * 100 if not prior.empty else None

    prev = d.iloc[-2] if len(d) > 1 else None
    mom = (latest / float(prev) - 1) * 100 if prev else None

    print(f"\n  rows            {len(df)}  ({df['month'].iloc[0]:%b %Y} → {latest_month:%b %Y})")
    print(f"  latest          ${latest / 1_000_000:.3f}tn  ({latest_month:%B %Y})")
    print(f"  record high     ${peak / 1_000_000:.3f}tn  ({peak_month:%B %Y})")
    print(f"  vs record       {pct_of_peak:.1f}%")
    if yoy is not None:
        print(f"  year-over-year  {yoy:+.1f}%")
    if mom is not None:
        print(f"  month-over-month{mom:+.1f}%")

    # Mirror the dashboard's own thresholds so the import doubles as a check.
    print()
    if pct_of_peak >= 99 and (yoy or 0) >= 25:
        print("  ⚠  RECORD HIGH AND RISING FAST — the dashboard will flag this HIGH.")
    elif pct_of_peak >= 95 and (yoy or 0) >= 15:
        print("  ⚠  Leverage building — the dashboard will flag this ELEVATED.")
    else:
        print("  ✓  Leverage not at an extreme by the dashboard's thresholds.")


def main() -> None:
    ap = argparse.ArgumentParser(description=__doc__,
                                 formatter_class=argparse.RawDescriptionHelpFormatter)
    ap.add_argument("--xlsx", type=Path, default=DEFAULT_XLSX,
                    help=f"FINRA spreadsheet (default: {DEFAULT_XLSX.relative_to(HERE)})")
    ap.add_argument("--csv", type=Path, default=DEFAULT_CSV,
                    help=f"CSV to write (default: {DEFAULT_CSV.relative_to(HERE)})")
    ap.add_argument("--months", type=int, default=0,
                    help="Keep only the most recent N months (0 = keep all history)")
    args = ap.parse_args()

    if not args.xlsx.exists():
        raise SystemExit(
            f"Spreadsheet not found: {args.xlsx}\n"
            "Download it from "
            "https://www.finra.org/investors/insights/investing/margin-statistics"
        )

    print(f"Reading {args.xlsx}")
    df = load(args.xlsx)

    if args.months > 0:
        df = df.tail(args.months).reset_index(drop=True)
        print(f"  trimmed to the last {args.months} months")

    args.csv.parent.mkdir(parents=True, exist_ok=True)
    with args.csv.open("w") as fh:
        fh.write(CSV_HEADER)
        df.to_csv(fh, index=False, date_format="%Y-%m-01")

    print(f"Wrote {args.csv}")
    summarise(df)
    print("\nRestart the dashboard (or press Refresh data) to pick this up.")


if __name__ == "__main__":
    main()
